baseURL = "https://anhhhtran.netlify.app"
defaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "en"
paginate = 5
theme = "hugo-theme-texify"
title = "Anh's Personal Page"

disqusShortname = ""
googleAnalytics = ""
pygmentsUseClasses = true

[author]
name = "AnhTran"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"
  weight = 1

[[menu.main]]
  identifier = "post"
  name = "Posts"
  url = "/"
  weight = 2
  
[[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/post/"
  weight = 3


[params]
  customCSS = []
  dateFormat = "2006-01-02"
  description = "TeXify"
  enableFullRSS = true
  enableHanEmph = true
  enableMathjax = true
  favicon = "/favicon.ico"
  keywords = ["hugo", "latex", "theme"]

# see https://utteranc.es for installation guide
[params.utterances]
  enable = false
  repo = ""
  issue_term = "pathname"
  label = "Comment"
  theme = "github-light"
